exclude:
  - "/vendor/"

# Site settings
title: SecuRT
subtitle: "Conférences & Capture the flag"
email: securt-ufc@gmail.com
name: SecuRT
description: > 
  SecuRT est un évènement de sécurité informatique organisé par le département RT de l'université de
  Franche-Comté. Chaque année, rencontre avec des professionels du monde du hacking, conférences, et 
  Capture The Flag
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://securt.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.jpg"

# Build settings
markdown: kramdown
#paginate: 5
#paginate_path: "/page:num/"

social:
  - name: Twitter
    icon: twitter
    username: TheBenCentra
    url: https://twitter.com/secuRT
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: SecuRT
    url: https://github.com/SecuRT
    desc: Fork me on GitHub
    share: false

protocols:
    twitter_image: "assets/logo.png"
