exclude:
  - "/vendor/"

# Site settings
title: SecuRT
subtitle: "Conférences & Capture the flag"
email: securt@univ-fcomte.fr
name: SecuRT
description: > 
  SecuRT est un évènement de sécurité informatique organisé par le département RT de l'université de
  Franche-Comté. Chaque année, rencontre avec des professionels du monde du hacking, conférences, et 
  Capture The Flag
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://securt.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.jpg"

# Build settings
markdown: kramdown
#paginate: 5
#paginate_path: "/page:num/"

social:
  - name: Facebook
    icon: facebook
    username: Facebook
    url: https://www.facebook.com/secuRT2014
    desc: Follow us on Facebook
    share: true

  - name: Twitter
    icon: twitter
    username: Twitter
    url: https://twitter.com/SecuRT_Montbe
    desc: Follow us on Twitter
    share: true

protocols:
    twitter_image: "assets/logo.png"
